export enum RiskCategory {
  // Customer Type Risks
  IRANIAN_INDIVIDUAL = 'IRANIAN_INDIVIDUAL',
  FOREIGN_INDIVIDUAL = 'FOREIGN_INDIVIDUAL',
  LEGAL_ENTITY = 'LEGAL_ENTITY',

  // Geographic Risks
  GEOGRAPHIC_BIRTH = 'GEOGRAPHIC_BIRTH',
  GEOGRAPHIC_RESIDENCE = 'GEOGRAPHIC_RESIDENCE',
  GEOGRAPHIC_TRANSACTION = 'GEOGRAPHIC_TRANSACTION',

  // Activity Risks
  OCCUPATION = 'OCCUPATION',
  BUSINESS_TYPE = 'BUSINESS_TYPE',
  PEP_STATUS = 'PEP_STATUS',

  // Financial Risks
  MONTHLY_INCOME = 'MONTHLY_INCOME',
  MONTHLY_REVENUE = 'MONTHLY_REVENUE',
  EXPECTED_ACTIVITY = 'EXPECTED_ACTIVITY',

  // Service Risks
  SERVICE_TYPE = 'SERVICE_TYPE',
  SERVICE_METHOD = 'SERVICE_METHOD',
  REMOTE_SERVICE = 'REMOTE_SERVICE',

  // Relationship Risks
  CUSTOMER_RELATIONSHIP = 'CUSTOMER_RELATIONSHIP',
  AGE_ESTABLISHMENT = 'AGE_ESTABLISHMENT',

  // Transaction Risks
  STR = 'STR',
  CTR = 'CTR',
}
